version: "3"
services:
  poke_database:
    hostname: database
    container_name: poke_database
    image: postgis/postgis:16-master
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - ./data/database/dev:/var/lib/postgresql/data
    env_file:
      - .env

  poke_api:
    container_name: poke_api
    build:
      context: ./
    ports:
      - 7001:7001
    depends_on:
      poke_database:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
